### ISSUE TITLE
Verify condition fails on v5.2.4 with "HttpError: response.headers.entries(...) is not a function or its return value is not iterable"

### ISSUE THREAD

**Issue by ryansmith94** [semantic-release/github#129]
Hey, we updated to v5.2.4 and verifyCondition started to fail as shown in [our CircleCI build](https://circleci.com/gh/HT2-Labs/mural/2191). We've reverted back to v5.2.1 and everything is working again. From looking at the release notes I can't see that this was intended, any idea what the issue could be?

**Comment by gr2m** [comment]
The "response.headers.entries(...) is not a function" should be resolved now via https://github.com/octokit/request.js/pull/15. Maybe run `npm ls @octokit/request` in your CI to make sure you have [v2.1.2](https://github.com/octokit/request.js/releases/tag/v2.1.2) installed. If you have any kind of lock file, make sure to re-create it

**Comment by ryansmith94** [comment]
Planning to give this a try at some point today. Thanks for the quick reply guys 👍

**Comment by pvdlg** [comment]
Investigating a bit more, I think https://github.com/octokit/rest.js/pull/1136 is also required to fix that issue.

**Comment by ryansmith94** [comment]
Okay thanks for the update @pvdlg. We didn't get a chance to test this yesterday unfortunately.

**Comment by pvdlg** [comment]
Ok I'll close this issue then. Please re-open if that happens again.
