### ISSUE TITLE
Octokit dependency bump possibly should of been major

### ISSUE THREAD

**Issue by milesj** [semantic-release/github#132]
Octokit was upgraded from 15 to 16 in a patch version (https://github.com/semantic-release/github/releases/tag/v5.2.2), which has broken our GHE environment. According to this PR, it's an unintended side-effect (https://github.com/octokit/rest.js/issues/1127).

Not sure of the best approach here, but maybe major version bumps should coincide with a major release.

**Comment by gr2m** [comment]
Sorry for the trouble! I’d pin the version until https://github.com/octokit/rest.js/issues/1127 is resolved

**Comment by milesj** [comment]
@pvdlg While that may be true, at minimum perhaps a minor release? Patches denote bug fixes, and this isn't a bug fix, it's new functionality.

And when reviewing dependency updates, I and probably many others, don't dig into specific details about patch versions, as that's one of the selling points of patch versions.

**Comment by pvdlg** [comment]
This is not a new functionality, it's just an update to a more recent version of a dependency that was not not supposed to change anything other than adapting to the new API of `@octokit/rest.js`.

The bug is in `@octokit/rest.js`. If we knew there was a bug we would have fixed it before making the release.

**Comment by gr2m** [comment]
> And when reviewing dependency updates, I and probably many others, don't dig into specific details about patch versions. That would be far too much overhead.

@milesj you shouldn’t do, we make sure that dependencies we update don’t break anything. My understanding is that this time there was a bug that we missed, it doesn’t qualify as a reason for a breaking change. The whole idea of semantic-release is to take subjective assumptions out of what a "minor" or a "major" release is, instead we just ask 3 questions:

1. Does the change include a breaking change -> major version bump
2. If not, does the change include a new feature -> minor version bump
3. If not, does the change include bug fix -> patch version bump

Again I’m sorry that the new release broke something, but that can always happen I’m afraid
