### ISSUE TITLE
What are the minimum requirements for GH_TOKEN

### ISSUE THREAD

**Issue by protoEvangelion** [semantic-release/github#135]
When generating a GitHub token, what are the minimum scopes required?

I know the docs say "push access", but I am wondering specifically which boxes to check ha 😄 
![image](https://user-images.githubusercontent.com/20076677/49831201-28df5e00-fd48-11e8-8816-5e73e4c241f6.png)

**Comment by gr2m** [comment]
You can also add links to create a token directly:

- for a private repository: https://github.com/settings/tokens/new?scopes=repo
- for a public repository: https://github.com/settings/tokens/new?scopes=public_repo

**Comment by protoEvangelion** [comment]
Absolutely 😄 Thanks for the quick response! Will additional permissions be required for the git plugin?

**Comment by gr2m** [comment]
I don’t think so, I wouldn’t know for what :)

**Comment by gr2m** [comment]
I don’t think so
