### ISSUE TITLE
Publish as pre-release?

### ISSUE THREAD

**Issue by simlu** [semantic-release/github#152]
Is there a way to publish as github pre-release? I couldn't find any setting unfortunately.

Thank you! L~

**Comment by pvdlg** [comment]
This is supported in semantic-release version 16.0.0-beta. Please the corresponding doc on the `beta` branch.

**Comment by simlu** [comment]
@pvdlg I'm a little confused what this has to do with semantic release? Is this plugin deprecated? I thought it was responsible for Github releases? Does semantic release use a different plugin?

**Comment by gr2m** [comment]
See the upcoming version of this plugin in the beta branch: https://github.com/semantic-release/github/tree/beta, you can find out more about the upcoming semantic-release features, such as pre-releases, at https://github.com/semantic-release/semantic-release/issues/563

**Comment by simlu** [comment]
@gr2m Ah, the versions are tied together! Now this makes more sense. Sorry, the way that releases are done here was not clear to me at all. Thanks for the explanation.
