### ISSUE TITLE
Fails on "Invalid username or password" for git push permissions

### ISSUE THREAD

**Issue by lirantal** [semantic-release/github#157]
Hi,

Seeing an error about semantic-release not able to push to github, even though the build has a GITHUB_TOKEN env var. 
 
```
[semantic-release] › ✖  The command "git push --dry-run https://[secure]@www.github.com/lirantal/opn-shell.git HEAD:master" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/lirantal/opn-shell.git/'
```

Travis build: https://travis-ci.org/lirantal/opn-shell/jobs/483803564

What should I be looking into?

**Comment by pvdlg** [comment]
Either your token doesn't allow to push, or it has been incorrectly set in the Travis variable.

If you want to test you can try to run `git push --dry-run https://<YOUR_TOKEN>@www.github.com/lirantal/opn-shell.git HEAD:master`.
This command must success.

**Comment by lirantal** [comment]
That prompts to enter a username.
If I enter my github username it fails on `anonymous access denied`

**Comment by lirantal** [comment]
Ah found it!
The repo URL having a www prefix is what caused it to error out, removing that works well.

**Comment by gr2m** [comment]
> The repo URL having a www prefix

Maybe that is something we can catch with semantic-release? What do you think @pvdlg?

**Comment by pvdlg** [comment]
There is already a quite detailed message produced by semantic-release: https://travis-ci.org/lirantal/opn-shell/jobs/483803564#L569

I don't think catching the specific case of additional `www` in github URL is such a good idea. If we start handling this type of configuration errors that open the door to handle an infinite number of them. Answering the many support ticket we have, I can say that people are really creative in terms of finding way to improperly configure a URL...

And some people having trouble to admit they made a mistake would often answer with things like "It's not my fault if didn't read the doc, or read the logs, or tried to debug. It's your software having a bad user experience". And they would ask for adding a very specific error handling for the very specific misconfiguration they did.

Generally I would be favorable to do a lot to make a software more accessible and to reduce friction. But as semantic-release is primarily meant to be used by developers and people with at least a bit of Git experience, I don't think we shouldn't bend backward to handle every possible case of wrong repo URL.

We are already doing a lot in terms user feedback regarding misconfiguration:
- A bunch of detailed error messages with link to the doc: https://github.com/semantic-release/semantic-release/blob/master/lib/definitions/errors.js
- Each plugin also have their own list of error message with a lot of details
- The `@semantic-release/github` plugin opens an issue with all those detailed error messages
- We have troubleshooting section: https://github.com/semantic-release/semantic-release/blob/master/docs/support/troubleshooting.md
- And a FAQ: https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md
