### ISSUE TITLE
Next release version in assets path. 

### ISSUE THREAD

**Issue by sorokinsh** [semantic-release/github#158]
Are you interested in PR that adds ability to use variables in assets properties such as path and label?

**Comment by gr2m** [comment]
Can you share your use case? What would the code look like in order to use the new configuration options?

**Comment by sorokinsh** [comment]
My case is:
```  "publish": [{
    "path": "@semantic-release/github",
    "assets": [
      {"path": "build/${nextRelease.version}.zip", "label": "version: ${nextRelease.version}"}
    ]
  }],
```

**Comment by gr2m** [comment]
Looks good to me, make sure to update the docs.

@pvdlg any objections?

**Comment by pvdlg** [comment]
Assets are attached to a GitHub release that contains the version already, so it seems redundant.
Can you clarify what value it would bring to  include the version in the asset name or label?

**Comment by sorokinsh** [comment]
The value is naming convention for attached files.

**Comment by pvdlg** [comment]
I'm sorry but I don't really understand...Having a naming convention for the sake of it doesn't bring any value... How a naming convention that includes the version would bring value in the context of a GitHub release that is already named after the version?

**Comment by bddckr** [comment]
The value is in users downloading the attached file. The user will be updating over and over and thus ends up with multiple archives. At that point it is helpful to have the version included in that file name.

I have the same requirement but I am just attaching the npm tarball (but zipped instead) which already includes the version name in the file name. A lot of my users are neither really familiar with npm, nor with VCSs or GitHub. For them upgrading the software is often done by just downloading from the releases (which is exactly what it's for) but they will not understand how to easily figure out the version of the downloaded release. With the version in the file name the issue doesn't even crop up for them.

**Comment by sorokinsh** [comment]
My full example is:
```
 "prepare": [{
    "path": "@semantic-release/exec",
    "cmd": "./scripts/prepare.sh ${nextRelease.version}" // it's work here 
  }],
  "publish": [{
    "path": "@semantic-release/github",
    "assets": [
      {"path": "build/${nextRelease.version}.zip", "label": "module bundle"} // but not here 
    ]
  }],
```
I use `build/*.zip` Instead of `build/${nextRelease.version}.zip` but it's not safe.

**Comment by sorokinsh** [comment]
> The value is in users downloading the attached file. The user will be updating over and over again and thus ends up with multiple archives. At that point it is helpful to have the version included in that file name.
> 
> I have the same requirement but I am just attaching the npm tarball (but zipped instead) which already includes the version name in the file name. A lot of my users are neither really familiar with npm, nor with VCSs or GitHub. For them upgrading the software is often done by just downloading from the releases (which is exactly what it's for) but they will not understand how to easily figure out the version of the downloaded release. With the version in the file name the issue doesn't even crop up for them.

true

**Comment by pvdlg** [comment]
Ok understood, make sense. Thanks for the explanation.

**Comment by tehshane** [comment]
+1 for this. Use case in my example is attaching a packaged Electron app to the release with a name like `MyAwesomeApp-v1.0.0.exe`.

Wouldn't be the end of the world to coerce Electron to create `MyAwesomeApp.exe` but it risks ambiguity to which version of the app is getting attached to the release.

Thanks!

**Comment by coderbyheart** [comment]
Hei, I propose #211, what do you think about the placeholder `%RELEASE%` and the handling of the release tag string in filenames (`v1.0.0` :arrow_right:  `v1_0_0`)? If you are fine with that, I'll update the docs as well.

**Comment by gr2m** [comment]
Why would you replace the `.` with `_`?

**Comment by coderbyheart** [comment]
I guess this is my personal taste and technically not neccessary. I removed that behaviour from the PR.

**Comment by zypA13510** [comment]
I don't think #218 fully covered this. Even though we can use variables in label and name now, we still can't use it in **path**, which is part of the original request.

**Comment by coderbyheart** [comment]
True, but OP clarified the use case later as

> The value is naming convention for attached files.

and this is achieved in this PR: the filenames attached to a GitHub release can have the version string in them.

**Comment by zypA13510** [comment]
My situation is simpler, I think. I have configured `@semantic-release/npm` to output tarball to a directory, now I need to upload `${pkg.name}-${pkg.version}.tgz` from that directory to GitHub. Package name don't change often (if at all) so we can ignore that, but version...

Right now, I have to either a) run a script using `@semantic-release/exec` to rename the file or b) use glob pattern e.g. `build/*.tgz`, and as noted by OP, it would be safer if we can use `build/mypkg-${nextRelease.version}.tgz`.

**Comment by melsawy93** [comment]
Is there an update on this? facing this issue.

**Comment by hollowsunhc** [comment]
I am also facing a similar issue, where the filename depends on the version determined by @semantic-release/commit-analyzer
