### ISSUE TITLE
Create a release with assets as draft prior to releasing it

### ISSUE THREAD

**Issue by paddie** [semantic-release/github#163]
This is related to PR #160 (I've not looked at the actual code) and the general approach of publishing as a draft while attaching assets to the release, instead of publishing the release prior to the release _actually_ being finalised - as in, having the assets the release should contain.

Your arguments against including it are valid, but I am unsure that there will actually be _two_ events triggered as a result of a draft->release promotion. From the documentation for the Github Release Event [here](https://developer.github.com/v3/activity/events/types/#releaseevent) it states that the webhook event is only triggered when a release is in fact _published_, not when the release is created as a draft.

I've not tested that that _is_ in fact the case, however there is a field in the payload called `draft: <boolean>` that would indicate if the release is in fact a draft or not. My personal opinion is that respecting that field would be the _proper_ way of handling any downstream systems responding to new releases that contains any form of payloads. Additionally, it would simplify any services that is working of off that release and expecting _multiple_ assets to be available.

I'd be very keen to hear your thoughts on this, and I appreciate your work on this tool immensely!

Patrick

**Comment by pvdlg** [comment]
I don't know what `published` exactly means in the GitHub API documentation. Maybe a draft release can be published...? You will have to test to be sure.

The use case described in #160 seems really specific and there is other solutions (that I proposed in this ticket) that are more adapted.

Every modification made in semantic-release has a long term impact:
- Added complexity
- More scenario to test
- Complex scenario to test (we would have to make sure somehow that a future change in the GitHub events won't break other workflow)
- More documentation/option creating confusion among users and more support load on our side

So I don't think we will make any changes to support such specific scenario, especially if that change look a lot like a workaround.

**Comment by paddie** [comment]
That is precisely what it means. As stated [here](https://help.github.com/en/articles/creating-releases), the flow that Github is promoting is to create a release as a draft, and then release it after all dependencies that are part of the release are attached to it.

From our perspective, a release is dirty until no more releases are added to it, the `release draft` -> `actual release` promotion is the idiomatic and Github promoted way of signalling precisely that a new release is in fact ready to be considered for whatever downstream processing is required.

I'll try to address your recommended workarounds in order:

> * Change your bots to wait a little bit when receiving the new release notification
This will fail in the general case if a certain release turns out to take longer to upload or fails and requires a re-try at some point.

> * Change your bot to react to an asset being added rather than on a new release
This would work, but would make it hard to determine when "all dependencies" have been added, meaning one would have to perform a combination of your first approach of waiting until the release reaches some sort of steady-state

> * Use the `@semantic-release/exec` plugin to send a notification to your bots on the `success` step
> * Replace your bot by a script triggered by `@semantic-release/exec` on the `success` step
This to me seems even more hackish. It allows one to signal a bot, but requires anyone using this to implement some other incoming channel to a bot, rather than simply listening to GH events (which most CI/CD systems would do by default).

I can also document that CI tools such as [AppVeyor](https://www.appveyor.com/docs/deployment/github/) (the default `draft: false` means a draft that is promoted to a release after assets have been uploaded. `draft: true` means a release gets released as a draft and needs to be manually promoted) and [Travis](https://docs.travis-ci.com/user/deployment/releases/#draft-releases-with-draft-true) support this approach to release creation by default due to this very reason.

**Comment by gr2m** [comment]
Hi @paddie, I’ve talked to Pierre and if you like we can add the following changes

1. If there are no assets to be uploaded, no changes
2. If there are assets to be uploaded, create the release as draft, then upload all assets, then publish release.

Would that address all your use cases? Do you want to get a pull request going?

**Comment by pmrcunha** [comment]
Hi @gr2m, that would work :)
I can grab #160 and change it to the current behavior when there are no assets. I'll make a new PR as soon as I've done it.

Thank you both for reconsidering this.

**Comment by paddie** [comment]
@gr2m thanks for picking this up <3

I think I can leave the work in @pmrcunha 's capable hands?

**Comment by madsgodvinjensen** [comment]
@gr2m Would you be able to look over the referenced PR? Just so we can move on with this from our side.

**Comment by gr2m** [comment]
Apologies, I totally missed that. Thanks for the ping!
