### ISSUE TITLE
GitHub Action support

### ISSUE THREAD

**Issue by gr2m** [semantic-release/github#182]
I’d like to make semantic-release work within GitHub actions out of the box

```workflow
action "npx semantic-release" {
  uses = "docker://timbru31/node-alpine-git"
  runs = "npx"
  args = "semantic-release"
  secrets = ["GITHUB_TOKEN", "NPM_TOKEN"]
}
```

The `NPM_TOKEN` needs to be configured, but `GITHUB_TOKEN` should work with the one provided by GitHub action.

But when I run the action, I get the following error

> EGHNOPERMISSION The GitHub token doesn't allow to push on the repository octokit/routes

The problem is that the token is not an OAuth token, but an GitHub App installation access token, because that’s how it’s implemented I assume. 

The verification works by checking the respone of `github.repos.get()` which for the GitHub Action returns 

```json
...
  "permissions": {
    "admin": false,
    "push": false,
    "pull": false
  },
```

Although the token has code write permission to the repository.

The token itself is easily distinguished: it starts with `v1.`, e.g. `v1.1234567890123456789012345678901234567890`.

We could also just check if `process.env.GITHUB_ACTION` is set, see [Environment variables](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/). But people can pass their own tokens so that’s not guaranteed.

I’d suggest we check for both.

If both is true, we can just assume that it has write access.

I’ll do some testing myself

**Comment by gr2m** [comment]
That did the trick for the verification step

```diff
diff --git a/lib/verify.js b/lib/verify.js
index 8b1617f..86758b3 100644
--- a/lib/verify.js
+++ b/lib/verify.js
@@ -52,6 +52,12 @@ module.exports = async (pluginConfig, context) => {
   } else if (githubToken && !errors.find(({code}) => code === 'EINVALIDPROXY')) {
     const github = getClient({githubToken, githubUrl, githubApiPathPrefix, proxy});
 
+    // https://github.com/semantic-release/github/issues/182
+    if (githubToken.substr(0, 3) === 'v1.' && process.env.GITHUB_ACTION) {
+      // We are good
+      return;
+    }
+
     try {
       const {
         data: {
```

I have yet to see it publish, I’ll update this issue once it did.

**Comment by zeke** [comment]
How did this turn out?

I'd like to set up GitHub-Actions-powered `semantic-release` on one of the modules I maintain: https://github.com/github-modules/github-url-to-object/pull/38

**Comment by gr2m** [comment]
Oh it totally worked, I use it for octokit/routes. You can install my fork:
https://github.com/octokit/routes/commit/50e99c84e6367ec6cdbdb0256741d16260abe3b7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45

Sorry that I forgot to update the issue. I’ll setup a PR

**Comment by pvdlg** [comment]
Isn't it a bug on GitHub side? It's weird that `github.repos.get()` return `"push": false` even though you actually have push permission.

**Comment by gr2m** [comment]
It is an implementation detail, the token you get in GitHub Actions is an app installation token, and there is no way to retrieve permissions as an installation right now.

I’m not sure if it’s a bug or a design decision, but I know folks are thinking about to make this easier. For the time being, I’d implement the workaround.

**Comment by pvdlg** [comment]
Ok. Checking `isNil(env.GITHUB_ACTION)` seems better than checking for `v1` in the token. I'm guessing GitHub can change the format of token anytime (at some point it will be come `v2` I imagine).

**Comment by activescott** [comment]
For others who find this... The other related fix to make semantic-release work within a GitHub Action is at https://github.com/semantic-release/semantic-release/commit/038e640d5e4231b3062c60565676bb2cdfbebd98 and this is not yet on the beta/v16 branch as of version `16.0.0-beta.22` (see https://github.com/semantic-release/semantic-release/blob/v16.0.0-beta.22%40beta/lib/get-git-auth-url.js).

**Comment by mkotsollaris** [comment]
I am trying to make `semantic-release` work for my project https://github.com/Trulioo/trulioo-react but I get this:

```
[5:29:17 PM] [semantic-release] › ✖  The command "git push --dry-run https://github.com/Trulioo/trulioo-react HEAD:master" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Trulioo/trulioo-react/'
[5:29:17 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
.
[5:29:17 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[5:29:17 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[5:29:17 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository Trulioo/trulioo-react.

[5:29:18 PM] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository with URL https://github.com/Trulioo/trulioo-react.
```

Any idea how I can properly authenticate myself when using github actions?

**Comment by gr2m** [comment]
You need to set the `GITHUB_TOKEN` environment variable from `secrets.GITHUB_TOKEN`. See https://github.com/octokit/core.js/blob/master/.github/workflows/release.yml for reference
