### ISSUE TITLE
Github Plugin Working with SSH Keys

### ISSUE THREAD

**Issue by rykard95** [semantic-release/github#187]
Hi,

I need a way for this plugin to work with Github SSH keys instead of personal access tokens.

Thanks

**Comment by gr2m** [comment]
Can you explain your use case with more details? Is this for GitHub Enterprise?

I don’t think you can use SSH keys for authenticating against the GitHUb API, which is something we rely on, e.g. for creating releases on the GitHub repository

**Comment by rykard95** [comment]
Hi yes,

So for our Github Enterprise, we need to have a federated user (human or system) created in order to log into Github and generate a personal access token. This means that we need to create a system user for the purposes of semantic-release. This system user expires every 90 days and we would have to create a new user in order to generate a new personal access token, and create a user takes time for us. We are working with our federation team to address this issue, but we thought it would be good to get a conversation started on this end as well. If we were able to use SSH keys instead of personal access tokens, we could decouple ourselves from this federated system. There are of course drawbacks, and we would still want to rotate the SSH Keys every 90 days as security best practices. I haven't looked into how authentication works for the Github API, but I can do some research on my end as well.

Thanks!

**Comment by gr2m** [comment]
This plugin is using GitHub’s API, can you authenticate against the GitHub API using an SSH key in GitHub enterprise?

**Comment by pvdlg** [comment]
Closing as no response was provided.
It doesn't seems http APIs can be called with ssh keys for authentication.
