### ISSUE TITLE
How to get release url in successComment?

### ISSUE THREAD

**Issue by jgeurts** [semantic-release/github#195]
I'm trying to write a successComment with the release url, but it doesn't seem to be populating correctly. Any pointers for where I could find it?

I tried:

`:tada: This ${issue.pull_request ? 'pull request' : 'issue'} is included in [version ${nextRelease.version}](<github_release_url>) :tada:`

and

`:tada: This ${issue.pull_request ? 'pull request' : 'issue'} is included in [version ${nextRelease.version}](${nextRelease.url}) :tada:`

Both do not replace with a url, unfortunately.

**Comment by pvdlg** [comment]
See the documentation for [successcomment](https://github.com/semantic-release/github#successcomment).

There is a `releases` array passed with an entry for each publication of a release (npm, GitHub, etc...) with the URLs.

Those URLs come from the plugins that made the publication and not all of them set one (`@semantic-release/npm` and `@semantic-release/github` does, but `@semantic-release/git` doesn't for example).

**Comment by jgeurts** [comment]
If anyone else comes across this, I used the following to get the github release url:

```
:tada: This ${issue.pull_request ? 'pull request' : 'issue'} is included in [version ${nextRelease.version}](${releases.filter(release => /github\.com/i.test(release.url))[0].url}) :tada:
```
