### ISSUE TITLE
404 during validation

### ISSUE THREAD

**Issue by ttretau** [semantic-release/github#196]
I receive the error "EMISSINGREPO The repository .. doesn't exist. " during verification.
I wonder if the parameters for get repos of octokit are exchanged, as they have to be "owner, repo"..
See here:
https://github.com/semantic-release/github/blob/30d5175a0a52dcf3f7e0af62f270919f92d5d1b3/lib/verify.js#L69

**Comment by travi** [comment]
i would recommend confirming that your token is made available to semantic-release and that the token has the appropriate privileges. 404 often means that you don't have the proper access in order to not leak existence to someone that shouldn't know if the repo exists or not.

**Comment by ttretau** [comment]
I verified that by calling this one directly: https://developer.github.com/v3/repos/#get
With same token I got 
```
..
  "permissions": {
    "admin": true,
    "push": true,
    "pull": true
  },
..

```

**Comment by pvdlg** [comment]
What is the `repository.url` configured in your `package.json`?
Is it the actual URL of your repo?

Please run semantic-release with `--debug` and provide the logs.

**Comment by ttretau** [comment]
Ah, I think perhaps debug revealed that the problem is not on this line anymore:
 `semantic-release:git Error: Command failed: git push  --dry-run ... HEAD:master remote: Invalid username or password. fatal: Authentication failed for..`
I have to figure out although the verify step must have worked now. Thanks, closing the issue.

**Comment by ttretau** [comment]
Just for the record and perhaps future tip: The problem was my config of `"githubApiPathPrefix": "/api/v3/"` for Github Enterprise, which resulted to 404. "githubApiPathPrefix": "/api/v3" without ending slash fixed it.

**Comment by pvdlg** [comment]
@gr2m we pass to `@octokit/rest` the concatenation of `githubUrl` and `githubApiPathPrefix` and we don't trim extra `/` at the end of `githubApiPathPrefix`. So we could pass either `https://github.com/semantic-release/github//api/v3` or `https://github.com/semantic-release/github//api/v3/`, depending on the user setting.

Shouldn't `@octokit/rest` works with both?
