### ISSUE TITLE
[HttpError]: Unable to create comment because issue is locked

### ISSUE THREAD

**Issue by gr2m** [semantic-release/github#221]
Logs: https://github.com/octokit/rest.js/runs/252397386#step:8:110

I think logging a warning is enough, it might be common enough for issues / pull requests to be locked that it should result in a failure.

**Comment by pvdlg** [comment]
You mean that it should **not** result in a failure right?

Would catching the `403` be too generic? Is there other situation that might end up with a 403 for the comment creation?

**Comment by pvdlg** [comment]
btw, I wish the GitHub API doc would mention the expected errors with status code and body.
The doc for [comment creation](https://developer.github.com/v3/issues/comments/#create-a-comment) mention only the passing case...

**Comment by gr2m** [comment]
> Is there other situation that might end up with a 403 for the comment creation?

I'm not sure 🤔 Maybe we should check for the `issue is locked` string, too, just to be sure?

>  I wish the GitHub API doc would mention the expected errors with status code and body.

Yes. Things might improve through adaption of OpenAPI Spec, but it will take a while.

**Comment by pvdlg** [comment]
> I'm not sure 🤔 Maybe we should check for the issue is locked string, too, just to be sure?

Checking for a string seems not great...the message could change anytime...it's probably different for a PR...and there might be other similar cases where one is forbidden to add a message (user ban? restriction?).

Put it an other way, is there any case of 403 that we want to result in a build fail?
I would say no as commenting a PR/issue is not part of the release per say, but more a notification thing that we do as an extra.
We [already consider all 404 as not a reason for failure](https://github.com/semantic-release/github/blob/7e56da87cca6dc9e2b45d1b5ed2974517dad291d/lib/success.js#L107) so I think we can do the same for 403s.

**Comment by gr2m** [comment]
Very good point, let's do that.
