### ISSUE TITLE
Releases do not get published to GitHub Marketplace

### ISSUE THREAD

**Issue by abatilo** [semantic-release/github#224]
When using this plugin and a new release is published, in the case that the item being released can be published to the GitHub Marketplace (like for example a GitHub Action), the latest release will NOT be published to the GitHub Marketplace.

Instead, you have to manually go and edit the latest release and check the box that says to publish to the Marketplace, then save the changes to the release.

**Comment by gr2m** [comment]
There is nothing we can do about it, there is no API to publish a release to Marketplace. Please contact support@github.com so they know about your requirement

**Comment by UziTech** [comment]
I think this issue should stay open until there is an API and it gets fixed.
