### ISSUE TITLE
Incorrect peerDependency range for beta branch

### ISSUE THREAD

**Issue by hershmire** [semantic-release/github#231]
I'm trying to get the latest semantic-release beta branch working but noticed that this repo's peerDependency for `semantic-release` doesn't include it's beta releases:

https://github.com/semantic-release/github/blob/beta/package.json#L85

```
"peerDependencies": {
  "semantic-release": ">=16.8.0 <17.0.0"
}
```

I'm thinking it should be more like this (https://github.com/semantic-release/git/blob/beta/package.json#L78)?

```
"peerDependencies": {
  "semantic-release": ">=16.0.0-beta <17.0.0"
}
```

**Comment by pvdlg** [comment]
Fixed in #232
