### ISSUE TITLE
Fails with missing GitHub token when --dry-run and --no-ci

### ISSUE THREAD

**Issue by snebjorn** [semantic-release/github#261]
When running with `--dry-run --no-ci` I get this fatal error

```shell
[semantic-release] » i  Start step "verifyConditions" of plugin "@semantic-release/github"
[semantic-release] [@semantic-release/github] » i  Verify GitHub authentication
[semantic-release] » ×  Failed step "verifyConditions" of plugin "@semantic-release/github"
[semantic-release] » ‼  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[semantic-release] » ×  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository <REDACTED>.

AggregateError: 
    SemanticReleaseError: No GitHub token specified.
```

I was expecting thous options to make the plugin play nice :)

**Comment by pvdlg** [comment]
The goal of `--dry-run` is to make sure the real run will work on your CI so we make the verification.
 The `@semantic-release/github` plugin requires a `GH_TOKEN` environment variable to be set and you don't have one so it report that error.

**Comment by snebjorn** [comment]
@pvdlg the docs for the **--no-ci** states that it should skip that verification.

> skip Continuous Integration environment verifications

[docs](https://github.com/semantic-release/semantic-release/blob/ec516a34bf18ea529cc8f1a603d7568702929543/docs/usage/configuration.md#ci)
> ### ci
> 
> Type: `Boolean`<br>
> Default: `true`<br>
> CLI arguments: `--ci` / `--no-ci`
> 
> Set to `false` to skip Continuous Integration environment verifications. This allows for making releases from a local machine.
> 
> **Note**: The CLI arguments `--no-ci` is equivalent to `--ci false`.

**Comment by lucien-perouze-cezembre** [comment]
I have the same error, I don't have @semantic-release/github installed nor CI yet it fails. I just want to release my package from my computer to begin tests without having to configure a CI pipeline.

**Comment by JuanmaMenendez** [comment]
Any update/workaround on this?

**Comment by ivanji** [comment]
Not sure why this is closed - The issue still persists, I'm not even using github anywhere - my repo is on BitBucket and I have a private registry, nowhere in my config I'm using this plugin but I keep getting 

```
[semantic-release] [@semantic-release/github] » i  Verify GitHub authentication
[11:55:21 am] [semantic-release] » ×  Failed step "verifyConditions" of plugin "@semantic-release/github"
[11:55:21 am] [semantic-release] » ‼  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[11:55:21 am] [semantic-release] » ×  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository [bit_bucket_repo_url_replaced_here_for_privacy].

AggregateError: 
    SemanticReleaseError: No GitHub token specified.

**Comment by deanshelton913** [comment]
I am releasing from gitLAB (having NOTHING TO DO with ANYTHING on gitHUB) and i am getting this:
```
[11:48:43 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[11:48:43 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
[11:48:43 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[11:48:43 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[11:48:43 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[11:48:43 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.
Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository deanshelton913/evmq.
[11:48:43 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
```
Of course there is no github token, I set a GITLAB token... What the heck does any of this have to do with gitHUB?

**Comment by 13OnTheCode** [comment]
Does it mean that I cannot use semantic-release if I don't use CI?

**Comment by travi** [comment]
> Does it mean that I cannot use semantic-release if I don't use CI?

https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-run-semantic-release-on-my-local-machine-rather-than-on-a-ci-server

**Comment by BinToss** [comment]
How do I test if everything *except* `GH_TOKEN` is working properly? Or how do I make `ENOGHTOKEN` treated as a warning during dry runs?
