### ISSUE TITLE
New releases don't trigger GitHub actions event

### ISSUE THREAD

**Issue by saitho** [semantic-release/github#264]
I'm trying to combine semantic-release and GitHub actions.
After semantic-release creates a new release I want to run additional actions via GH actions.
However the "published" event is not triggered.

I've set up a test repository: https://github.com/saitho/workflow-test
The ["Publish" workflow](https://github.com/saitho/workflow-test/actions?query=workflow%3A%22Publish+workflow%22) should get triggered after a release was published.

I examined the octokit/rest package here: https://github.com/saitho/workflow-test/blob/master/index.js . Creating a release with that script will raise the release.published event and run my workflow. So the API seems to work fine.

Not sure why it doesn't work with semantic-release/github though, as to me it seemed to use the same methods as I did here.

Can anyone confirm that issue? :)

**Comment by gr2m** [comment]
The problem is that events triggered by GitHub Actions don't trigger GitHub Actions. Try to exchange the `secrets.GITHUB_TOKEN` to a personal access token from your account, in this line:

https://github.com/saitho/workflow-test/blob/6e2b8e490c08bea17228caccbe4bc63163846a62/.github/workflows/test-and-release.yml#L41

That used to work as a workaround but I'm not sure if it still will

**Comment by saitho** [comment]
Works. Added a note to README in PR #265

**Comment by tacnoman** [comment]
I have the same problem. I want to trigger another action when creating a tag, but I cannot make work.

I have a file with this:

```yml
on:
  push:
    tags:
      - '*'
```

And I created a personal access token (PAT) and used in GITHUB_TOKEN, but doesnt work. How can I do to use the PAT and trigger?

I must create another environment variable?

```yml
      - name: Run semantic release
        env:
          DEBUG: semantic-release:github
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release
```

**Comment by tacnoman** [comment]
Worked for me adding this:

```yml
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # <<<--- This line
```
