### ISSUE TITLE
GitHub default url should be api.github.com

### ISSUE THREAD

**Issue by lholota** [semantic-release/github#271]
Hi, I am using the semantic-release/github in a couple of my repositories it started throwing the following error lately:

```
[10:08:30 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /action/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
...
```

Based on my investigation, this is caused by passing incorrect url to Octokit (i.e. https://github.com instead of https://api.github.com) as mentioned in [this issue in Octokit](https://github.com/octokit/rest.js/issues/544).

As it seems, the default url is github.com. Mitigation is possible using the GH_URL or GITHUB_URL environment variables. But given that this is the default value which might be used by many people, I think this should be updated. 

Logs can be found in one my repo's [CI/CD run](https://github.com/homecentr/docker-base/runs/677683025?check_suite_focus=true)

**Comment by gr2m** [comment]
This was fixed by https://github.com/semantic-release/github/pull/269, make sure to update your lock file so you get the latest version.

**Comment by Silthus** [comment]
I have the same error and already updated to `7.0.6`. I also cannot get it to work with the `GITHUB_API_URL` environment variable. No matter what I do, the release fails.

Also one other strange thing I noticed: when the release fails it does not open an issue on Github, but creates a tag and publishes a package. This makes the release half broken and every time the action fails I need to bump the version. Is this intended or am I doing something wrong?

https://github.com/Silthus/sLib/runs/699757716?check_suite_focus=true#step:8:73

**Comment by gr2m** [comment]
I think it only creates an issue if the `verify` step failed, which it didn't in this case.

I'm not sure why it still gets the config wrong, but it definitely sends the request to `https://github.com` instead of `https://api.github.com`:
https://github.com/Silthus/sLib/runs/699757716?check_suite_focus=true#step:8:99

**Comment by Silthus** [comment]
Any idea what I can do about the failing releases?

The strange think is that I have another repository using the exact same build process and that works: https://github.com/Silthus/spigot-plugin-template

**Comment by gr2m** [comment]
I don't know what the problem could be and I can't investigate further I'm afraid. My first guess woudl be that somehow you still have an outdated semantic-release version running somewhere ... In the build that failed, you are using a semantic-release action: https://github.com/homecentr/docker-base/actions/runs/105566028/workflow#L16-L19, maybe try to use `run: npx semantic-release` instead

**Comment by babblebey** [comment]
Addressed in https://github.com/semantic-release/github/pull/269
