### ISSUE TITLE
Change release author name

### ISSUE THREAD

**Issue by supersnager** [semantic-release/github#286]
Hi,
Please see attached screenshot, now in my repository on releases list author name is shown as github-actions.
is it possible to set author to github user name e.g. my name, or user  which does last commit, so it will looks like manual release from github interface?
![release-author](https://user-images.githubusercontent.com/6375504/93360171-a7353200-f843-11ea-9020-ca101d5a86b2.png)

**Comment by gr2m** [comment]
You can achieve that by not using the built-in `GITHUB_TOKEN` secret, but instead creating a secret in the repository such as `SUPERSNAGGER_PAT` set to a personal access token of yours, then use `secrets.SUPERSNAGGER_PAT` instead of `secrets.GITHUB_TOKEN` in your workflow file

**Comment by supersnager** [comment]
@gr2m It's working. Thank You :+1:

**Comment by stefan-karlsson** [comment]
This would actually be a awesome feature. 
Would be nice to be able to override the GIT_COMMITTER_NAME the same way the `@semantic-release/git` package does it.

**Comment by gr2m** [comment]
it's not possible. You don't set an author for a release, the creator of the release is automatically derived based on the authentication. If you use `secrets.GITHUB_TOKEN`, then the creator is `@github-actions`. If you want someone else to be shown as the creator, use a token for this particular user
