### ISSUE TITLE
How to get the green `Latest release` text on the most recent release

### ISSUE THREAD

**Issue by sbernheim4** [semantic-release/github#290]
Perhaps a silly question but I've looked all over to find out how to get the green `Latest release` bubble text on the most recent publish release in github. 

For example right now 7.1.1 is the latest version of this plugin and on the [releases page](https://github.com/semantic-release/github/releases) shows the green `Latest release` bubble text. 

How can this be done via semantic release configs. I have releases correctly being published to NPM and they are properly tagged on github. They are just missing this little bubble.

**Comment by travi** [comment]
that should be the default behavior. here is another example of one of my personal projects that uses the default semantic-release config and it has the marker: https://github.com/form8ion/lift/releases

**Comment by sbernheim4** [comment]
Thanks @travi
