### ISSUE TITLE
Publish to GitHub Packages on release

### ISSUE THREAD

**Issue by pathurs** [semantic-release/github#291]
I cannot see any direct support for publishing to the GitHub Packages, is there support for this, or any plans to do so?

**Comment by gr2m** [comment]
yes, it should just work:tm:

Set the registry in an `.npmrc` as described at https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages

1.  In the same directory as your `package.json` file, create or edit an `.npmrc` file to include a line specifying GitHub Packages URL and the account owner. Replace `OWNER` with the name of the user or organization account that owns the repository containing your project.

    ```
    registry=https://npm.pkg.github.com/OWNER
    ```

**Comment by pathurs** [comment]
@gr2m I'll try this tonight, if it works I'll let you know. I might even try and write up some documentation and submit a PR

**Comment by babblebey** [comment]
Address in https://github.com/semantic-release/github/issues/291#issuecomment-705124249
