### ISSUE TITLE
Create Milestones

### ISSUE THREAD

**Issue by estahn** [semantic-release/github#314]
Would be great if a release creates a Milestone and attaches all issues to that particular milestone.

**Comment by gr2m** [comment]
Interesting use case. I don't think it would be in the scope of this plugin, but you could build a dedicated plugin for this functionality.

**Comment by estahn** [comment]
@gr2m I suppose it could be a different plugin, I just figured instead of tagging each issue with "release" and adding a comment with the release it is in, you could just create a milestone and attach the issue to that milestone.

**Comment by gr2m** [comment]
> I just figured instead of tagging each issue with "release" and adding a comment with the version details it is in

Yeah I do like that idea, but not everyone would like semantic-release to create milestones, so we would still need to implement the existing flow.

It'd be great if you cold implement this as a plugin, I'd like to test it myself to see how it feels. We can consider of adding it to the core plugin in future

**Comment by estahn** [comment]
@gr2m Fair enough, I will give it a go.

**Comment by babblebey** [comment]
Hopefully addressed by https://github.com/semantic-release/github/issues/314#issuecomment-940405139
