### ISSUE TITLE
Feature request: exclude PRs with specific labels from commenting

### ISSUE THREAD

**Issue by ylemkimon** [semantic-release/github#361]
This is somewhat similar to #359.

There may be some PRs that don't need release comments, such as dependency management and chores. It'd be nice to exclude them by labels like:
```diff
--- a/lib/success.js
+++ b/lib/success.js
@@ -28,6 +28,7 @@ module.exports = async (pluginConfig, context) => {
     successComment,
     failComment,
     failTitle,
+    excludeCommentLabels,
     releasedLabels,
     addReleases,
   } = resolveConfig(pluginConfig, context);
@@ -45,7 +46,8 @@ module.exports = async (pluginConfig, context) => {
     const releaseInfos = releases.filter((release) => Boolean(release.name));
     const shas = commits.map(({hash}) => hash);
 
-    const searchQueries = getSearchQueries(`repo:${owner}/${repo}+type:pr+is:merged`, shas).map(
+    const labelQuery = excludeCommentLabels ? excludeCommentLabels.map((label) => `+-label:"${label}"`).join('') : '';
+    const searchQueries = getSearchQueries(`repo:${owner}/${repo}+type:pr+is:merged${labelQuery}`, shas).map(
       async (q) => (await github.search.issuesAndPullRequests({q})).data.items
     );
```

**Comment by melink14** [comment]
I don't even think labels are needed; it was very surprising that this was posted for commits which were not part of the release spec.

Given that the plugin is given information on which commits are considered 'worth making a release' for, maybe there should be an option for 'only include version changing commits'?

<I can start a new issue for this but added it here because the reasoning for wanting it is the same; exclude chore/docs and other PRs which may not go to users>

**Comment by babblebey** [comment]
This is now possible in configuration with the `successCommentCondition` property following the merge of https://github.com/semantic-release/github/pull/874... You can set your conditions through [lodash templates](https://lodash.com/docs#template) with  access to the release `context` object

```js
successCommentCondition: "<% return issue.label?.includes('specific-label-name') %>"
```

The above config sets you up for only comment/label issues and pull-requests with specific label, if you intend it to be PRs alone then you want to state for PRs alone like so....

```js
successCommentCondition: "<% return issue.pull_request && issue.label?.includes('specific-label-name') %>"
```
