### ISSUE TITLE
Fix grammar in `/lib/get-fail-comment.js`

### ISSUE THREAD

**Issue by HonkingGoose** [semantic-release/github#366]
I noticed the bot uses a bit of bad grammar here on line 32:

https://github.com/semantic-release/github/blob/3b1edd6a769787604d2dcdb4dd103cfc0ed85e61/lib/get-fail-comment.js#L32-L35

I think it would be better if it said:

```
If you are not sure how to resolve this, here are some links that can help you:
```

I'm not sure if I can fix this with a PR to the `lib/get-fail-comment.js` file or if I also need to do something with tests, or change some other files as well?

**Comment by travi** [comment]
thanks for bringing it to our attention. if you are open to creating a PR to update it, we would certainly appreciate it. i'm not sure if any tests would be impacted by changing the message, but running the verification should be able to answer that question. if all of the verification passes, i don't think there would be other things worth digging for that would need updates.

**Comment by HonkingGoose** [comment]
I'll go make a PR and see where that gets me. 😄
