### ISSUE TITLE
Support `discussion_category_name` when creating a release

### ISSUE THREAD

**Issue by ylemkimon** [semantic-release/github#371]
From https://docs.github.com/en/rest/reference/repos#create-a-release:
> `discussion_category_name`: If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "[Managing categories for discussions in your repository.](https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository)"

**Comment by RaphaelNeumann** [comment]
I'm need that feature too.

**Comment by gr2m** [comment]
pull request welcome! We can add a `discussionCategoryName` name option.
