### ISSUE TITLE
Hitting rate limits

### ISSUE THREAD

**Issue by moltar** [semantic-release/github#377]
On a large repo, when releasing for the first time, I am hitting a rate limit:

```
AggregateError: 
    HttpError: API rate limit exceeded for installation ID 227XXXX.
```

I think there should be a delay and retry mechanism for this.

This should be simple enough to add with something like `p-retry` package.

**Comment by gr2m** [comment]
`@semantic-release/github` is currently using its own throttling logic, it was created before there was https://github.com/octokit/plugin-throttling.js/. Replacing the built-in logic with `@octokit/plugin-throttling` might likely resolve the problem, it's much more battle tested by now.

PRs welcome!

**Comment by gr2m** [comment]
fixed via https://github.com/semantic-release/github/releases/tag/v8.0.8
