### ISSUE TITLE
semantic release is failing because of Octokit change

### ISSUE THREAD

**Issue by MahaZaid** [semantic-release/github#386]
<img width="1031" alt="Screen Shot 2021-07-06 at 4 14 31 PM" src="https://user-images.githubusercontent.com/20710308/124615137-41b73e00-de75-11eb-95db-e60f2fcf1e06.png">

**Comment by gr2m** [comment]
Hi Maha 👋🏼 This is a deprecation warning, not an error. What version of `semantic-release` do you use? I don't think this warning should still occur in the latest version

**Comment by babblebey** [comment]
Closing this as its gone stale 😉
