### ISSUE TITLE
Support globs for assets

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/github#4]
https://github.com/cheton/github-release-cli and the Travis GitHub deploy provider support this.
One use case is it's nice to suffix the binary with the version string.

**Comment by pvdlg** [comment]
Looking at the sources of https://github.com/cheton/github-release-cli it seems globs are supported only for deleting assets. But the Travis github deployment tool does support globs.

Do you have a use case in which such feature would be useful ? Is it common to release more than a few files?
Usually a project would have a step (most like in the `prePublish` script) that creates the assets. And if there is multiple file to release it would probably create a zip file and upload it.
The problem with allowing globs is to define what to do with directories. Should we upload each file in individually?

I though about creating a zip file when a directory is configured. But it's not necessarly what the user want. Maybe a user wants to upload a zip of the `dist` directory, maybe she/he wants to upload each individual file in it.

My point is that it might open the door to a very complex feature (lot of code, lot of options, lot of tests, lot of issues/feature requests) for something that probably belongs to the build process and not `semantic-release`.

Regarding suffixing the assets, what is the use case? The asset will be uploaded to a release on Github that by definition is a version. What would be the point of releasing asset named `mylib-1.0.0.min.js` in release 1.0.0? The end user would have to rename the file to `mylib.min.js`.
Also suffixing is not necessary that simple. Should it be `mylib-1.0.0.min.js`? or `mylib.min-1.0.0.js` or `mylib.min.js-1.0.0`?

Again this feature belongs to the build process more than the release process.
The dist file should be generated in a `prePublishOnly` script and each user can do their custom naming convention / ziping / etc there.
