### ISSUE TITLE
Fail to add comment to issues on other repo

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/github#45]
See https://travis-ci.org/semantic-release/github/jobs/345779998#L506

We should probably exclude issues from other repo anyway, as we don't want to be invasive and add comments to someone else repo.

**Comment by germanattanasio** [comment]
First, thanks for this amazing library. 🙌 

Can we have an option like `commentInOtherRepos` for this? I want to use this feature to write a comment in other repositories if possible.

**Comment by gr2m** [comment]
You could write your own plugin for this. You are the first to ask for this feature, so it’s unlikely that we add it to the official github plugin

**Comment by maniax89** [comment]
@gr2m how would one write a plugin to do this? i also see a need for either an option to allow comments in other repos or maybe a `allowedRepos` list to match on?

**Comment by gr2m** [comment]
You can start out with https://github.com/semantic-release/github, make the changes you want, then publish it so that it can be used as a drop-in replacement for `@semantic-release/github`
