### ISSUE TITLE
Document minimum permissions for GitHub Actions `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by ericcornelissen** [semantic-release/github#456]
With GitHub Actions it's possible to configure the permissions of the `GITHUB_TOKEN` ([both in repository settings and in workflow files](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/)). Depending on how it's configured, this plugin might not work. In particular, setting the token to only have read access (or lower) will _probably_ result in the plugin failing to create a GitHub release. It would be convenient if the required permissions of the token are documented in the README (or elsewhere) so that users don't have to guess and try.

Based on prior experiences I had with creating GitHub releases in GitHub Actions with limited permissions, only the `contents: write` permission is required (see the [GitHub Actions docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) for a full overview of permissions).

If someone else already tried to configure the permissions and knows the minimum permissions this plugin needs, please share it :slightly_smiling_face: If not, I'm currently in the process of configuring the permissions of the `GITHUB_TOKEN` for a project that uses semantic releases, including this plugin. Once I managed to create a release successfully I can add a note about the permissions I used to the documentation of this plugin.

**Comment by gr2m** [comment]
`contents: write` is required to create the tags and releases.

`issues:write` and `pulls:write` are required for the comments and to create issues in cases a release failed.

A pull request to add this information to the README would be much appreciated
