### ISSUE TITLE
[Rate-limiting]: How many calls (or multiple based on conditions) are run by the plugin?

### ISSUE THREAD

**Issue by seedy** [semantic-release/github#486]
# Description

Hey folks, first of all, I wanted to say thanks for the toolkit!

We recently decided to use it for https://github.com/traefik/faency, which is a component library developed at TraefikLabs.

We have a huge infrastructure with many OSS projects.

We're investigating on some rate-limiting issues we had recently.

In this process, I'd like to know more about the number of calls fired to the github API.

From reading the code in [publish.js](https://github.com/semantic-release/github/blob/master/lib/publish.js), I already expect atleast 3 api calls to:
1. create release
2. upload assets
3. update release

I know there's also:
- 1 api call on each PR included in a release

Am I wrong here? Could there be more, with our current setup?

Following is our setup for releasing with the tool.

## Setup

- we release from PRs containing a single squashed commit
- we use default plugins with preset `conventionalcommits`

Here's the config in our `package.json`
```
  "release": {
    "branches": [
      "master",
      "next"
    ],
    "plugins": [
      [
        "@semantic-release/commit-analyzer",
        {
          "preset": "conventionalcommits"
        }
      ],
      [
        "@semantic-release/release-notes-generator",
        {
          "preset": "conventionalcommits"
        }
      ],
      "@semantic-release/npm",
      "@semantic-release/github"
    ]
  },
```

**Comment by gr2m** [comment]
fixed via https://github.com/semantic-release/github/releases/tag/v8.0.8
