### ISSUE TITLE
[feature] customize the release details

### ISSUE THREAD

**Issue by its-dibo** [semantic-release/github#498]
is there an option to customize the release title and details like this:
```
["@semantic-release/github",{
  release:{
    details: `<details><summary>changes</summary> ${changelog} </details>`
 }
}
```
also, we need the variable `${changelog}`

**Comment by char0n** [comment]
Yeah, customizing `Release title` would be great. Voting +1

**Comment by halkeye** [comment]
https://github.com/semantic-release/github/pull/704

**Comment by babblebey** [comment]
Addressed in https://github.com/semantic-release/github/pull/704
