### ISSUE TITLE
Make GitHub push occur after new git tag commit is made

### ISSUE THREAD

**Issue by thedanchez** [semantic-release/github#499]
I'm trying to setup my `semantic-release` config in such a way that, when the `semantic-release-bot` generates the commit containing the message `chore(release): x.x.x [skip ci]` -- that is when I want the GitHub release to be generated pointing to that same commit.

What is happening currently for me is the following:

```
* 9eabd8b - (tag: v1.3.0) chore(release): 1.3.0 [skip ci] (34 minutes ago) <semantic-release-bot> <-- release tagged by git
* 1a9296c - feat(release): more fixes to publish script (37 minutes ago) <Daniel Sanchez>. <-- release tagged in GitHub :(
```

As you can see above, when I look at the releases in GitHub for my repo, I see the *previous* commit tagged in GitHub and not the chore commit containing the manifest file changes (for `package.json`, etc.). 

Is there a way to achieve this outcome?

**Comment by travi** [comment]
the behavior you describe as desired should be the default. [this release](https://github.com/traverson/traverson/releases/tag/v8.0.2) from a project that i maintain is related to the tag on the commit where semantic-release committed the changes to the changelog file
