### ISSUE TITLE
success plugin: Document criteria for PR match

### ISSUE THREAD

**Issue by pmowrer** [semantic-release/github#50]
After the `success` plugin was added, `semantic-release` posts (or attempts to) a comment to every single PR in the entire repository. I assumed this isn't the intended behavior, but it's not clear to me why this is happening? What are the criteria used to identify eligible PRs?

**Comment by pvdlg** [comment]
We didn't experienced that with the repo on which we were testing.
The eligible PR/issues are determined as follow:
- All PR associated with commits part of the release (from last release to head)
- All issues/PRs referenced in the body of those PRs
- All issues/PRs referenced in the body of the commits part of the release

**Comment by pvdlg** [comment]
Do you have an example of the problem? If possible a link to the repo and to the CI jobs that created the issue?

**Comment by pmowrer** [comment]
Thanks for the clarification. Unfortunately its a private project. I intend to look into why this happened but unfortunately won't have the bandwidth for a little while.

**Comment by pvdlg** [comment]
@pmowrer did you find an issue regarding semantic-release? Or should we close this issue?

**Comment by pmowrer** [comment]
Sorry, haven't had a chance to do semantic-release dev in a while. We turned `success` plugin off for now and everything works great. I'll reopen when I have more info.
