### ISSUE TITLE
[feature] option to disable releases

### ISSUE THREAD

**Issue by GeeWizWow** [semantic-release/github#503]
Hi, my team do a lot of prereleases which can lead to a lot of release spam. 

Would you consider the contribution of an option to disable releases? This would in effect disable the `publish` and `addChannel` steps of the plugin.

Thinking something along these lines:

| Option | Description | Default |
|---------|--------------|---------|
| `releases`  | Publishes a GitHub release, optionally uploading file assets. Set to `false` to disable, or supply a [branch name](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md#name) to only publish releases on specific branches. |  `true`  |

**Comment by ivanji** [comment]
I don't think this is something that should be done by this plugin - you should check your workflow, and also take a look at `commit-analyzer`, there you can specify the release rules: https://github.com/semantic-release/commit-analyzer#releaserules

**Comment by GeeWizWow** [comment]
@travi @ivanji Thanks both the input, much appreciated!
Closing this in favor of using release-rules. Thanks
