### ISSUE TITLE
Glob in `assets` field flattens paths... is this intentional?

### ISSUE THREAD

**Issue by thezimmee** [semantic-release/github#58]
This is more of a question than an issue, since maybe my configuration is wrong. My build creates files that have the same name; something like this:

```
dist/
    lib/
        merge.js
        merge.min.js
    browser/
        merge.js
        merge.min.js
```

In my release config, with `github.assets` configured as a glob:

```js
assets: ['dist/{lib,umd,browser,module}/*.js']
```

or

```js
assets: 'dist'
```

or

```js
assets: ['dist/**/*']
```

my build in Travis CI would throw this [Validation Failed / name exists error](https://api.travis-ci.org/v3/job/358599836/log.txt). Files _were_ actually getting published to NPM and GitHub, but the GitHub release was flattening the paths, so only one of the `merge.js` and `merge.min.js` files was actually getting published to github.

When I configure each file individually in `github.assets`, like this:

```js
assets: [{
    name: 'lib.merge.js'
    path: 'dist/lib/merge.js'
} ...]
```

the error goes away and all files are correctly released in github. I guess my questions are:

1. _Is this intended behavior?_
2. Is there a way to keep the folder structure for my github release?

It would be much easier to use a glob so I wouldn't have to explicitly set each file's name and path... and that would be the behavior I would expect from a glob. Any help on how to do this is much appreciated.

**Comment by pvdlg** [comment]
Yes that's the intended behavior and it's not semantic-release that impose this behavior but the way Github releases works.
GitHub releases accept a list of file with unique names but no directory not paths. As a result the path in which the files live on the file system is irrelevant in the GitHub releases as only files are handled.

semantic-release could try to "guess" the name of the file based on it's path, but there is no guarantee that's the behavior all users want. For example some might want `dist/lib/merge.js` to be named `merge.js` (in case there is no duplicates) or `lib-merge.js` or `lib.merge.js` or `dist-lib-merge.js` or `dist.lib.merge.js`, etc...
There is not really a good way to "guess" what the name should be, and in most cases the file name will be unique. This is why the choice that make most sense is to just use the file name.

If you want to use only a glob without having to specify the filename you would have to modify your build script to produce files with unique names, for example `dist/lib.merge.js`, `dist/lib.merge.min.js`, `dist/browser.merge.js` and `dist/browser.merge.min.js` and use the config `assets: ['dist/**/*.js']`.

**Comment by pvdlg** [comment]
See the GitHub API documentation for more info: https://developer.github.com/v3/repos/releases/#upload-a-release-asset.
The `name` parameter is for file name, not file path.

**Comment by thezimmee** [comment]
👍 Very clear, thank you @pvdlg!
