### ISSUE TITLE
Issue not getting labelled if link

### ISSUE THREAD

**Issue by stayko** [semantic-release/github#586]
My semantic release config:

```
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/github",
      "@semantic-release/npm",
      "@semantic-release/git"
    ],
    "prepare": [
      "@semantic-release/npm",
      {
        "path": "@semantic-release/git",
        "assets": [
          "package.json"
        ],
        "message": "chore(app release): ${nextRelease.name} [skip required checks]\n\n${nextRelease.notes}"
      }
    ],
    "branches": [
      {
        "name": "main",
        "prerelease": false,
        "channel": "prod"
      },
      {
        "name": "dev",
        "prerelease": "dev",
        "channel": "dev"
      },
      {
        "name": "staging",
        "prerelease": "staging",
        "channel": "staging"
      }
    ]
  },

```

`semantic-release` version 19.0.2 

I've noticed that if the PR mentions the issue like this:

`- Closes https://github.com/some-org/some-repo/issues/123`

Semantic release doesn't label the issue (it usually adds `released on @channel` label), only the PR. However if in the PR I write:

`Closes #123` 

Then it works. I'm guessing it can't parse the issue number from the link?

**Comment by babblebey** [comment]
Hello @stayko,

I couldn't reproduce this issue, everything seem to work just fine after attempting in 2 tries/variations, kindly see my demo PR to its linked issue below. 

- https://github.com/babblebey/sr/pull/12
- https://github.com/babblebey/sr/pull/10

Also, kindly confirm whether you still have this issue 😉
