### ISSUE TITLE
Upload to marketplace is not an option

### ISSUE THREAD

**Issue by tanmen** [semantic-release/github#629]
Are there any plans to add an upload option to marketplace for use in releases of github actions?

**Comment by travi** [comment]
that would go beyond the intent of this plugin, but could possibly make sense in a separate plugin targeting github actions more directly

**Comment by Th3S4mur41** [comment]
@tanmen did you figure out a way to automate this?
I wasn't even able to find a [documented API call](https://docs.github.com/en/apps/publishing-apps-to-github-marketplace/using-the-github-marketplace-api-in-your-app/rest-endpoints-for-the-github-marketplace-api) to publish to marketplace... [The only docs I found point to the UI](https://docs.github.com/en/apps/publishing-apps-to-github-marketplace/using-the-github-marketplace-api-in-your-app/rest-endpoints-for-the-github-marketplace-api).

**Comment by gr2m** [comment]
Unfortunately there is no API to update the version in marketplace. I do the same as @tanmen in conjunction with https://github.com/gr2m/semantic-release-plugin-github-breaking-version-tag

**Comment by Th3S4mur41** [comment]
Thanks guys. I currently use [Actions Tagger](https://github.com/marketplace/actions/actions-tagger) to set both the major version tag and also the `latest` tag.

I created [a discussion in the GitHub community to ask for a way to publish to Marketplace to be added to the API](https://github.com/orgs/community/discussions/69630).
Feel free to upvote and comment 😉
