### ISSUE TITLE
Markdown missing

### ISSUE THREAD

**Issue by brettz9** [semantic-release/github#637]
Hi,

Since applying, our [releases](https://github.com/gajus/eslint-plugin-jsdoc/releases/) are not showing up in Markdown. Is that not handled by this plugin?

Is there a problem with our [rc file](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/.releaserc)?

Thanks!

**Comment by travi** [comment]
without the release-notes-generator plugin, markdown release notes are not generated. please review the default plugins list: https://semantic-release.gitbook.io/semantic-release/usage/configuration#plugins

**Comment by brettz9** [comment]
Thank you!
