### ISSUE TITLE
http-proxy-agent issue on v8.0.8 -> v8.0.9 update

### ISSUE THREAD

**Issue by cdev-bazaar** [semantic-release/github#642]
We've lately started seeing issues in our CI pipeline (run using `cycjimmy/semantic-release-action`) :

```
[9:42:15 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.5
[9:42:15 AM] [semantic-release] › ✖  An error occurred while running semantic-release: /runner/_work/_actions/cycjimmy/semantic-release-action/v2/node_modules/http-proxy-agent/dist/index.js:44
        this.proxyHeaders = opts?.headers ?? {};
                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/runner/_work/_actions/cycjimmy/semantic-release-action/v2/node_modules/@semantic-release/github/lib/get-client.js:2:[26]({redacted repo}))
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:10[27]({redacted repo}):10)
```

We traced this back to the update from v8.0.8 to v8.0.9, and the update from `http-proxy-agent` from v5 to v7 ([link to diff](https://github.com/semantic-release/github/compare/v8.0.8...v8.0.9)).

We've been able to fix our CI pipelines by locking the version to 8.0.8; but we've had to do this across multiple repos, which isn't ideal.
```
    extra_plugins: |
        @semantic-release/github@8.0.8
```

**Comment by gr2m** [comment]
The minimal required version is and was 14.17 for `@semantic-release/github@8.x.x`, and we are testing against it in our CI
https://github.com/semantic-release/github/blob/d78b44ab2d2e1b14ea9368892a278313beaed89e/.github/workflows/test.yml#LL16C14-L16C19

**Comment by gr2m** [comment]
Can you share a link to the build? We need to know the exact node version that was used

**Comment by travi** [comment]
[MDN shows](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility) optional chaining was added to node in v14.0.0. [node.green appears to align with that](https://node.green/#ES2020-features-optional-chaining-operator-----).

i agree that this error doesn't make sense given the details that we currently have.

**Comment by cdev-bazaar** [comment]
Unfortunately, this is a private repo, so I can't share the build link; but can confirm that the pipeline is pulling in Node v18 in the immediately preceding CI step..
Run actions/setup-node@v3 output:
```
Run actions/setup-node@v3
Attempt to resolve LTS alias from manifest...
Attempting to download 18...
Acquiring 18.[16](https://github.com/bazaarvoice/influenster-django/actions/runs/5142139440/jobs/9256284234#step:4:17).0 - x64 from https://github.com/actions/node-versions/releases/download/[18](https://github.com/bazaarvoice/influenster-django/actions/runs/5142139440/jobs/9256284234#step:4:19).16.0-4687330280/node-18.16.0-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /runner/_work/_temp/0a3d0101-b70f-44[19](https://github.com/bazaarvoice/influenster-django/actions/runs/5142139440/jobs/9256284234#step:4:20)-bf50-f25cb789806c -f /runner/_work/_temp/0b88c7b7-96e0-473d-a7ab-22fec57972d9
Adding to the cache ...
Environment details
  node: v18.16.0
  npm: 9.5.1
  yarn: 
```

**Comment by cdev-bazaar** [comment]
But as you stated, the action is pulling in v16 🤷‍♂️

**Comment by travi** [comment]
i think we need more information in order to reproduce this and investigate any further. are you seeing this behavior in more than just this project? i'm certain that there are more folks using the action that you referenced and we haven't seen other similar reports. finding other projects, ideally public, using this action and hitting the same error could possibly help narrow in on what is really going wrong. short of that, a public minimal reproduction repository could be a really big help.

**Comment by rsdmike** [comment]
We are seeing this message as well, here is a public repo that we see this in: 

https://github.com/open-amt-cloud-toolkit/ui-toolkit/

**Comment by rsdmike** [comment]
Moving from cycjimmy/semantic-release-action@v2 to @v3 fixed it for us.

**Comment by gr2m** [comment]
Thanks @rsdmike that explains it:
https://github.com/cycjimmy/semantic-release-action/releases/tag/v3.0.0

<img width="614" alt="" src="https://github.com/semantic-release/github/assets/39992/c5b030f5-3ca3-4540-956c-e87c6a640e17">

Upgrading to v3 is the fix. As there are no other changes, upgrade should be easy

**Comment by cdev-bazaar** [comment]
Ah. Thanks for this 😄
