### ISSUE TITLE
in node@16 installation fails because of @octokit/plugin-retry@4.1.4

### ISSUE THREAD

**Issue by existe-deja** [semantic-release/github#643]
[recent patch](https://github.com/octokit/plugin-retry.js/commit/52cf451c23b82898046f861b5806915e93561f98) version of @octokit/plugin-retry upgrade node version without triggering a major release.

**Comment by timbru31** [comment]
We have sadly the same issue, this breaks a lot of CI builds for us.

```
[3/5] 🚚  Fetching packages...
error @octokit/plugin-retry@4.1.4: The engine "node" is incompatible with this module. Expected version ">= 18". Got "16.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by existe-deja** [comment]
just froze the dependency in your package in the meaning time

**Comment by travi** [comment]
it looks like this should be resolved now in the octokit plugin directly: https://github.com/octokit/plugin-retry.js/pull/432. you may need to update your lockfile

in the future, please file issues like this against the offending package directly
