### ISSUE TITLE
Bug not adding label when successComment is set to false

### ISSUE THREAD

**Issue by fed-gren** [semantic-release/github#660]
I added an option to not add a success comment in this plugin.
The behavior I had in mind was to add a label to the pull request, but no comment.
But when I set the successComment option to false, it skipped adding the label.
Is this the correct behavior? If there's a setting I'm missing, please let me know.

```json
"@semantic-release/github",
{
  "releasedLabels": ["v<%= nextRelease.version %>"],
  "successComment": false
}
```

Before setting successComment to false
<img width="716" alt="image" src="https://github.com/semantic-release/github/assets/39091443/c91a5210-272a-4779-a1ea-5c6a2396cc82">

After setting successComment to false
<img width="870" alt="image" src="https://github.com/semantic-release/github/assets/39091443/7dc07421-725b-48b2-a1f7-c36c407063cf">

**Comment by travi** [comment]
the label and the successComment are currently controlled by the same setting. please search for existing issues and PRs
