### ISSUE TITLE
Tada emoji no longer resolved in comments

### ISSUE THREAD

**Issue by franky47** [semantic-release/github#754]
Comments posted about releases contain the `:tada: This PR is included in version 1.13.1 :tada:` headline, but GitHub no longer resolves the `:tada:` markers to the associated 🎉 emoji.

Example link to comment: https://github.com/47ng/next-usequerystate/pull/415#issuecomment-1846309757

This may be an issue with GitHub's markdown processor.

**Comment by franky47** [comment]
Seems like the issue is scoped to emoji shortcode posted via the GitHub API, I was able to reproduce on a [test message](https://github.com/franky47/actions-laboratory/issues/14).

GitHub bug report for tracking: https://github.com/orgs/community/discussions/78334

**Comment by travi** [comment]
this appears to be working again: https://github.com/semantic-release/env-ci/pull/322#issuecomment-1858856180
