### ISSUE TITLE
Seeing EMISMATCHGITHUBURL from the latest version which breaks our release build

### ISSUE THREAD

**Issue by flannanl** [semantic-release/github#885]
The latest version with the change: https://github.com/semantic-release/github/pull/878 is currently breaking our release build. We are using Travis CI to trigger our release build and we start to get `EMISMATCHGITHUBURL` even though our repository URL did not change. We are using Enterprise GitHub. Is there a way to show what is mismatching? We currently need to pin to version 10.1.1 to get our builds to work again.

**Comment by nandreanurag** [comment]
I believe this change only handles the package.json configuration file. If you use other configuration files like .releaserc or release.config.js, it will fail. Which configuration file are you using?

**Comment by flannanl** [comment]
I'm using the package.json. I don't have .releaserc or release.config.js in my repository. If there is a way to output the actual and the expecting repository URL, at least I have a better idea what's wrong. Right now, I have no idea what the URL looks like.

**Comment by nandreanurag** [comment]
Downgrade the package to npm install @semantic-release/github@10.1.1. This can be an interim fix for this issue

**Comment by jedwards1211** [comment]
@gr2m I can't seem to use an `https://` URL as required by this new change on CircleCI:
```
circleci@52eb909c3fee:~/project$ git remote set-url origin https://github.com/jcoreio/zod-forms.git
circleci@52eb909c3fee:~/project$ git remote -v
origin	ssh://git@github.com/jcoreio/zod-forms.git (fetch)
origin	ssh://git@github.com/jcoreio/zod-forms.git (push)
```
Even if I could, according to [the Git docs](https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories#switching-remote-urls-from-ssh-to-https), this would break CI releases anyway because after changing to an HTTPS URL,
> The next time you git fetch, git pull, or git push to the remote repository, you'll be asked for your GitHub username and password. When Git prompts you for your password, enter your personal access token

I think it would be better to only compare the `<owner>/<repo>` portion of the two URLs.

**Comment by jfairley** [comment]
SAME!

I had to list the previous version (10.1.1) in my package to get releases going.
