### ISSUE TITLE
Bump minimum bound for peer dependencies with `semantic-release`

### ISSUE THREAD

**Issue by babblebey** [semantic-release/github#902]
> Just a quick fyi to keep in mind: to use the newly added logger in core, we'll need to bump the minimum bound of the peer dependency, which is a breaking change

_Originally posted by @travi in https://github.com/semantic-release/github/pull/874#discussion_r1720828079_

**Comment by gr2m** [comment]
This one: https://github.com/semantic-release/github/blob/990bd7335df10153c9b87bf2be57db602b08def0/package.json#L103-L105

**Comment by gr2m** [comment]
The steps are

1. Add new API to `semantic-release` core package, which releases a new version
2. Replace `20.1.0` in the package.json file of this repository to the new version of `semantic-release` core from the 1st step
3. Release this change as a breaking version of `@semantic-release/github`
