### ISSUE TITLE
is .npmignore not respected?

### ISSUE THREAD

**Issue by grubyak** [semantic-release/github#97]
while `npm pack` shows expected list of files, when i do release the package contains all the files from the project including those mentioned in `.npmignore`

dependencies:
```
        "@semantic-release/changelog": "^3.0.0",
        "@semantic-release/commit-analyzer": "^6.0.0",
        "@semantic-release/git": "^7.0.1",
        "@semantic-release/github": "^5.0.1",
        "@semantic-release/release-notes-generator": "^7.0.0",
        "semantic-release": "^15.8.1"
```

my `.releaserc.json`:
```
{
    "branch": "master",
    "debug": true,
    "noCi": true,
    "npmPublish": false,
    "githubUrl": "...",
    "githubApiPathPrefix": "...",
    "repository": {
        "type": "git",
        "url": "..."
    },
    "verifyConditions": [
        "@semantic-release/changelog",
        "@semantic-release/github"
    ],
    "getLastRelease": "@semantic-release/git",
    "prepare": [
        {
            "path": "@semantic-release/git",
            "assets": [
                "package.json",
                "CHANGELOG.md"
            ],
            "message": "chore(release): releasing ${nextRelease.version}\n\n${nextRelease.notes}"
        }
    ],
    "publish": [
        {
            "path": "@semantic-release/github",
            "assets": [
                "package.json",
                "CHANGELOG.md"
            ]
        }
    ]
}
```

if `.npmignore` is not the right file to filter out things that are added to the package, how else can i do that? i also tried `files: [ ... ]` in `package.json` - also does not help

**Comment by pvdlg** [comment]
Your configuration doesn't even use the `npm` plugin and therefore don't publish on npm.
How is that even related to semantic-release?

**Comment by grubyak** [comment]
forgot to mention, that i am publishing on enterprise github (that's why `semantic-release/github`) - was assuming that same rules applies when creating a package, no matter if it's for npm or github, thus i mentioned `.npmignore`.

question remains: how to control which files will get to a package published on github?

**Comment by pvdlg** [comment]
`.npmignore` is an npm file as indicated by its name. It's used only by npm.

The `semantic-release/github` plugin will include in the Github release the files you configure in `assets`.

In addition GitHub will include a zip package of your entire repo with each release. That's a GitHub feature that is totally independent of semantic-release.

**Comment by grubyak** [comment]
@pvdlg thanks for the explanation, i found that you can filter out files from the package published in github by listing them with `export-ignore` flag in `.gitattributes` in the root of the repo
