### ISSUE TITLE
Custom successComment not being used

### ISSUE THREAD

**Issue by pathurs** [semantic-release/github#99]
I've only been using semantic-release for a few days, so I may not fully understand how it works, so this may just be my misunderstanding.

Here's a recent issue that was meant to use the below config: https://github.com/Colonise/DataSource/issues/29

I've configured my `package.json` like so:
```
"publish": [
    {
        "path": "@semantic-release/github",
        "successComment": "This ${issue.pull_request ? 'pull request has been included in' : 'issue has been resolved in'} **[release ${nextRelease.gitTag}](https://github.com/Colonise/DataSource/releases/tag/${nextRelease.gitTag})**!\\n\\nYou can install the **[npm package](https://www.npmjs.com/package/@colonise/datasource)** for ${nextRelease.gitTag} using `npm install @colonise/datasource@${nextRelease.version}`\\n\\n_Automatically generated by [semantic-release](https://github.com/semantic-release/semantic-release)._",
        "failTitle": "The automatic publishing of release ${nextRelease.gitTag} is failing"
    },
    "@semantic-release/npm"
]
```
Permalink:
https://github.com/Colonise/DataSource/blob/dd0b873927dd54b451b8c1976d8034d98c35e586/package.json#L100-L104

Cheers

**Comment by pvdlg** [comment]
The `successComment` is used in the `success` step and `failTile` is used in the `fail` step.
So you would have to configure those option in the appropriate steps or you can configure them directly at the root of the config object:
```json
{
  "release": {
    "successComment": "...",
    "failTitle": "..."
  }
}
```

**Comment by pathurs** [comment]
Thanks @pvdlg

Is there a place that shows example package.json configuration? I could not find a place.

If there's not, perhaps there could be an example project for each plugin that configures each possible option.

**Comment by pvdlg** [comment]
Yes: https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/plugins.md
Also in the doc of every plugins, e.g. https://github.com/semantic-release/github#usage
